//autogenerated:yes
//nolint:revive,lll
package main

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Commands struct {
    msg.Package `ros:"my_package"`
    Arm bool
    Mode string
    Forward int16
    Lateral int16
    Thrust int16
    Pitch int16
    Roll int16
    Yaw int16
    Servo1 int16
    Servo2 int16
}

