//autogenerated:yes
//nolint:revive,lll
package main

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Telemetry struct {
    msg.Package `ros:"my_package"`
    Timestamp int32
    BatteryVoltage float32
    Arm bool
    ImuGyroX int32
    ImuGyroY int32
    ImuGyroZ int32
    ImuGyroCompassX int32
    ImuGyroCompassY int32
    ImuGyroCompassZ int32
    Q1 float32
    Q2 float32
    Q3 float32
    Q4 float32
    Rollspeed float32
    Pitchspeed float32
    Yawspeed float32
    InternalPressure float32
    ExternalPressure float32
    Heading int32
}

